version: '3.8'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - client
    image: strapi-nginx-client
    container_name: strapi-nginx-client
    restart: always

  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    image: strapi-client
    container_name: strapi-client
    restart: unless-stopped
    environment: # FOR server.js
      NODE_PORT: 3000
