version: "3"
services:
  nginx-react:
    container_name: nginx-ecommerce-strapi-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
