version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - ui
    image: nginx-client
    container_name: nginx-client
    restart: unless-stopped
    networks:
      - app-network

  ui:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    image: nodejs-client
    container_name: nodejs-client
    restart: unless-stopped
    networks:
      - app-network
    environment:
      STRAPI_HOST: http://localhost:1337
      STRIPE_PUB_KEY: pk_test_51NgDYsCLZ8gkHkFvK1K3pUPOIIRApUSlmnWkcAyXbAZxtBqGEqMrAAmCsNxfOoppGEWu3tQ2JTwDrTo9qcJlmNjE00O2EgmWvQ
      NODE_PORT: 3000
