version: "3.8"

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:8080
    depends_on:
      - client
    image: nginx-client
    container_name: nginx-client
    restart: always

  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    image: nodejs-client
    container_name: nodejs-client
    restart: unless-stopped
    environment: # FOR server.js
      NODE_PORT: 3000
